%% Extract target detections from Vision Detection Generator log

% Target vehicle in the current driving scenario.
% Actor 1 is the ego vehicle, Actor 2 is the target vehicle.
targetActorId = 2;

% Detection log generated by scenario_sensor_model.slx
D = out.visionDetectionsLog;

% Number of valid detections at each simulation step.
numDetections = squeeze(D.NumDetections.Data);
numSamples = numel(numDetections);

% Result buffers.
time_sec = [];
target_x = [];
target_y = [];
target_vx = [];
target_vy = [];
false_positive_count = 0;

for k = 1:numSamples

    % Only the first NumDetections(k) slots are valid at this sample.
    n = numDetections(k);

    for detectionIdx = 1:n

        targetIndex = squeeze( ...
            D.Detections(detectionIdx) ...
            .ObjectAttributes.TargetIndex.Data(:,:,k));

        % False-positive detection
        if targetIndex < 0
            false_positive_count = false_positive_count + 1;
            continue;
        end

        % Ignore detections belonging to actors other than our target.
        if targetIndex ~= targetActorId
            continue;
        end

        detectionTime = squeeze( ...
            D.Detections(detectionIdx).Time.Data(:,:,k));

        measurement = squeeze( ...
            D.Detections(detectionIdx).Measurement.Data(:,:,k));

        % Ego Cartesian measurement:
        % [x; y; z; vx; vy; vz]
        time_sec(end + 1, 1) = detectionTime;
        target_x(end + 1, 1) = measurement(1);
        target_y(end + 1, 1) = measurement(2);
        target_vx(end + 1, 1) = measurement(4);
        target_vy(end + 1, 1) = measurement(5);
    end
end

targetDetections = table( ...
    time_sec, ...
    target_x, ...
    target_y, ...
    target_vx, ...
    target_vy);

disp(targetDetections(1:min(10,height(targetDetections)), :));

fprintf("Target detections: %d\n", height(targetDetections));
fprintf("False positives:   %d\n", false_positive_count);

csvPath = fullfile( ...
    fileparts(mfilename('fullpath')), ...
    'target_detections.csv');

writetable(targetDetections, csvPath);

fprintf("Detection CSV:     %s\n", csvPath);